<?php
/*
 * Copyright (c) 2013, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */
?>
<div id="besearch-toolbar" class="sly-toolbar">
	<div class="sly-toolbar-content">
		<div class="sly-form">
			<div class="fleft">
				<label for="besearch-article-name"><?php print t('article_name') ?>:</label>
				<input autocomplete="off" id="besearch-article-name" type="text" name="besearch-article-name" value="" class="sly-form-text" />
			</div>
			<fieldset>
				<form action="index.php?page=<?php print $page ?>" method="post">
					<input type="hidden" name="category_id" value="<?php print $categoryID ?>" />
					<input type="hidden" name="article_id" value="<?php print $articleID ?>" />
					<input type="hidden" name="clang" value="<?php print $clang ?>" />
					<?php print sly_Util_Csrf::renderInputTag() ?>

					<div class="fleft">
						<label for="besearch-article-id"><?php print t('id') ?>:</label>
						<div>
							<input type="text" name="besearch-article-id" id="besearch-article-id" class="sly-form-text" />
							<input class="sly-form-submit" type="submit" id="besearch-start-search" value="<?php print t('search') ?>" />
						</div>
					</div>
				</form>
				<form action="index.php" method="get">
					<input type="hidden" name="page" value="structure" />
					<input type="hidden" name="clang" value="<?php print $clang ?>" />
					<div class="fright" id="besearch_quicknavi">
						<label for="besearch-category-id"><?php print t('be_search_quick_navi') ?></label>
						<?php print $quickNavi->render() ?>
					</div>
				</form>
			</fieldset>
		</div>
	</div>
</div>
